# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='token',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
